# getkits.use - permision  /kit
lang:
  no-permission: "&cBrak uprawnien!"
  successfully-pick-up: "&aPomyslnie odebrano zestaw {name}!"
  no-permission-to-kit: "&cNie posidasz uprawnien do tego zestawu"
  cooldown: "&cMusisz odczekac {time} aby odebrac ponownie zestaw!"

sec: " {sec}s"
min: " {min}m"
hour: " {hour}h"
day: "{day}d"

format: "{d}{h}{m}{s}"

inv:
  title: "&0getKits - Zestawy"
  size: 27
  backgrounds:
    '1':
      material: BLACK_STAINED_GLASS_PANE
      displayname: "&7"
      lore: []
      slots: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]
